//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaymentProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRMRequest
    {
        public int CRMRequestID { get; set; }
        public System.Guid CustomerID { get; set; }
        public Nullable<int> ServiceCategoryID { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public string IssueDescription { get; set; }
        public int IssueType { get; set; }
        public Nullable<System.Guid> AssignedToAdmin { get; set; }
        public int CRMRequestStatus { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public int RecordStatus { get; set; }
        public string AdminNotes { get; set; }
    }
}
