//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaymentProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingDetail
    {
        public int TrainnerID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string PermanentAddress { get; set; }
        public string TemporaryAddress { get; set; }
        public int CourseOfInterest { get; set; }
        public int KnowAboutUs { get; set; }
        public string Others { get; set; }
        public string UGCollege { get; set; }
        public Nullable<decimal> UGPercentage { get; set; }
        public string PGCollege { get; set; }
        public Nullable<decimal> PGPercentage { get; set; }
        public string OQCollege { get; set; }
        public Nullable<decimal> OQPercentage { get; set; }
        public string YearOfExperience { get; set; }
        public string CurrentCompany { get; set; }
        public string TechnologyCurrentlyWork { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
    }
}
