//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaymentProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPaymentTransaction
    {
        public int UserPaymentTransactionID { get; set; }
        public int UserProfileID { get; set; }
        public System.DateTime PaymentDateTime { get; set; }
        public string AuthTransactionID { get; set; }
        public string AuthCardNumber { get; set; }
        public string AuthAuthorizationCode { get; set; }
        public bool Approved { get; set; }
        public decimal Amount { get; set; }
        public string InvoiceNumber { get; set; }
        public string AuthResponseCode { get; set; }
        public string AuthMessage { get; set; }
        public Nullable<bool> IsRefunded { get; set; }
    }
}
