//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaymentProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserServicesInvoice
    {
        public long UserServiceInvoiceID { get; set; }
        public decimal Credit { get; set; }
        public decimal Debit { get; set; }
        public long UserSubscriptionID { get; set; }
        public string MessageCode { get; set; }
        public string Message { get; set; }
        public string ResultCode { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> RefundStatus { get; set; }
        public Nullable<System.DateTime> RefundDate { get; set; }
        public Nullable<decimal> RefundAmount { get; set; }
        public string RefundReason { get; set; }
        public Nullable<long> RefundedBy { get; set; }
        public Nullable<long> RefundCode { get; set; }
        public string RefundMessage { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public int RecordStatus { get; set; }
    }
}
