//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaymentProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutomatedPaymentTransaction
    {
        public int AutomatedPaymentTransID { get; set; }
        public int AutomatedPaymentID { get; set; }
        public decimal Amount { get; set; }
        public bool Approved { get; set; }
        public string AuthorizationCode { get; set; }
        public string CardNumber { get; set; }
        public string InvoiceNumber { get; set; }
        public string Message { get; set; }
        public string ResponseCode { get; set; }
        public string AuthorizeTransID { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public Nullable<System.DateTime> RefundDate { get; set; }
        public Nullable<bool> IsRefunded { get; set; }
    }
}
