//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaymentProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRMRequestNote
    {
        public int CRMRequestNotesID { get; set; }
        public int CRMRequestID { get; set; }
        public string CRMUpdate { get; set; }
        public Nullable<int> CRMStatusChangeFrom { get; set; }
        public Nullable<int> CRMStatusChangeTo { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public int RecordStatus { get; set; }
    }
}
