//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaymentProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndexData
    {
        public long IndexDataID { get; set; }
        public int IndexDataTypeID { get; set; }
        public Nullable<int> Priority { get; set; }
        public string Description { get; set; }
        public string Title { get; set; }
        public string Path { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public int RecordStatus { get; set; }
        public string ThumbnailPath { get; set; }
    }
}
